### ISSUE TITLE
[high load avg during insert]

### ISSUE THREAD

**Issue by cha0sCat** [milvus-io/pymilvus#137]
**系统环境：**
**Ubuntu18.04 内核5.0**
**Docker 18**
**Milvus使用sqlite进行索引支持**
**启动了cache_insert特性**
  
  
**问题：我同时使用32台服务器直接远程连接到milvus实例进行insert操作(使用pymilvus)**
**然后出现了高负载的情况，大概在3.0左右，这甚至导致同服务器上的redis取出条目的时间高达5s..**
**iotop显示结果为jbd2持续占用io但是读写不大，milvus主进程写入速度90MB/s**
  
  
**究竟是什么任务导致的？**
我个人猜测有以下原因
 - 因为我启用了 cache_insert 特性
 - sqlite 的写入日志特性导致的 jbd2高占用
 - milvus 没有正确的应对高并发情况

**Comment by yhmo** [comment]
cache_insert设成true时，是让导入的数据落盘后立刻放进缓存，这样如果在同时做查询的时候就减少磁盘文件读入缓存的环节，理论上会让不间断地插入数据和不间断地查询的场景下表现好点，但我们测试下来感觉效果并不明显。按道理cache_insert设成true或false并不会对io有影响，我觉得你的场景下把cache_insert设成false也会出现高负载的情况。这32台机器是不间断地插入向量么？每次插入的向量条数是多少？每秒大概会有多少次insert操作？

**Comment by yhmo** [comment]
先明确一下，你说的这个cache_insert指的是milvus的server_config.yaml里的cache_insert_data这个选项吧？

**Comment by yhmo** [comment]
我的机器是nvme的磁盘，用iotop测milvus插入数据时最大写入速度大约是700MB/s，不过我是单客户端。

**Comment by cha0sCat** [comment]
我已确认问题
是sqlite的锅
将sqlite换位mysql后，负载迅速下降至0.05
代价是我的数据全没了

32台服务器均进行单条插入操作，速度不确定，大概每秒2-3条

**Comment by cha0sCat** [comment]
如果milvus有导出数据的功能就好了😁

**Comment by yhmo** [comment]
每秒不到一百条数据量，理论上应该对磁盘没什么压力才对，对于元数据管理来说压力也很小。sqlite有自己的WAL机制，可能会有写放大，但不至于成为瓶颈。虽然换mysql解决了，但感觉有点无法解释。
我们确实有一个issue是要做个工具把meta数据在mysql和sqlite之间互导，不过还没腾出人手去做。

**Comment by cha0sCat** [comment]
这个问题近在多服务器同时insert出现
我在单机导入1m测试数据的时候非常稳定快速

**Comment by cha0sCat** [comment]
又出现了，现在我使用mysql作为后端，mysql和milvus不在同一个服务器
开了56台服务器并行录入，当我录入到不到15万的时候，突然负载就开始升高

**Comment by cha0sCat** [comment]
在13万的时候，我还特地看一下，一点问题都没有，到将近15w突然负载就升高了

**Comment by cydrain** [comment]
Can you check which process occupy most of CPU resources when system load is high ?

**Comment by cha0sCat** [comment]
> Can you check which process occupy most of CPU resources when system load is high ?

CPU 负载并不高 Milvus主进程在40%左右 系统不超过100%

**Comment by cydrain** [comment]
Your question is: system load is too hight, and degrade redis performance.
If Milvus only occupies 40% CPU, what other CPUs are doing ?
System load is high means all CPUs are busy

**Comment by cha0sCat** [comment]
系统的负载高不代表cpu高, 而是待处理的任务对列较长
例如: io 阻塞, 内存不走导致的换页活动, 都会导致负载高

**Comment by yhmo** [comment]
It could be caused by milvus file merge action. 
Milvus continue flush insert data into disk at 1 second interval, and merge small files. The internal behavior is different for two scenarios:  insert 1M vectors in one batch or insert 1M vectors by multiple insert action. Since you have 56 clients, each client only insert 2~3 vectors one time, each second only about one hundred vectors inserted in to milvus, so milvus will continue flush insert data into disk and merge little files into big one(until big file size large than 1GB, defined by insert_buffer_size in the server_config.yaml), this is why IO load is high.
Please refer this article for more detail of Milvus data management: https://zhuanlan.zhihu.com/p/90812583
And I suggest to deploy Milvus to a single server, to avoid impact on other service(such as Redis).

**Comment by BossZou** [comment]
Not active. Close it. Reopen if there are more issue.
